name: Docker buildx

# on:
#   pull_request:
#     branches: master
#   push:
#     branches:
#       - master
#     tags:
#       - '*'

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      -
        name: Build and push
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t kegbot/server:latest \
            --push .
